### ISSUE TITLE
Negative assertions on captured messages

### ISSUE THREAD

**Issue by mMontu** [inkarkat/runVimTests#5]
Thanks again for sharing this plugin, I'm using it in [Crunch plugin](https://github.com/arecarn/crunch) and it is working very well!

I was thinking about how the captured messages (`testXXX.msgok`) works and noticed that in order to ensure no Vim error messages occurred in a test it would be necessary to insert some kind of zero width pattern like `\@!` between each assertion.

I think ensuring all tests that do not expects an Vim error message doesn't produce such message would make plugins more robust, but I'd like to hear your thoughts about it.

If this is a good idea I think there are some easier options to implement this behavior:
- a prefix for assertions on `testXXX.msgok` indicating they shouldn't match on any line of output
- check that no Vim error is expected by the absence of assertions matching `E\d+`, then flag Vim errors as test failure
- use a function that when called on the test triggers an additional argument to the `call vim ...  -c "RunVimMsgFilter" -c "quitall!" ...` which enables the negative assertion on that test

**Comment by inkarkat** [comment]
Interesting use case. In my plugins, I do proper error handling (whereever possible), so that the mapping or command itself will fail, and I can test that. However, for things like macros it would indeed be helpful to assert no Vim errors at all.
If I remember correctly, Vim also logs silenced error messages; this could be a problem.

**Comment by mMontu** [comment]
It's been a while since I wrote this issue. I don't recall the details, but I've probably applied some workaround.

**Comment by inkarkat** [comment]
@mMontu Thanks for responding and closing this; I'm currently going through some old issues and cleaning things up.
